exclude = [ "__pycache__", "*.jpg", "*.gif", "._*", ".AppleDouble", ".git", ".gitignore", ".ipynb_checkpoints", ".pylintrc", ".vscode", "*.exr", "*.pyc", "core", "*.egg-info", ".github", "data"]
include = []
max_file_size = 100000
