apiVersion: run.ai/v1
kind: RunaiJob
metadata:
  name: danmoral-inter-2
  labels:
    priorityClassName: "build" # Interactive Job if present, for Train Job REMOVE this line
    user: danmoral
spec:
  template:
    metadata:
      labels:
        user: danmoral # User e.g. firstname.lastname
    spec:
      hostIPC: true
      schedulerName: runai-scheduler
      restartPolicy: Never
      securityContext:
        runAsUser: 226647 # insert uid found in people.epfl in admistrative data
        runAsGroup: 11169 # insert gid as found in people.epfl in admistrative data
        fsGroup: 11169
      containers:
      - name: container-name
        image: ic-registry.epfl.ch/mlo/dani-mlo:v8
        workingDir : /mlodata1/danmoral/decentralized-DL
        command: ["/bin/bash"]
        args:
        - "-c"
        - "sleep infinity"
        resources:
          limits:
            nvidia.com/gpu: 1
        volumeMounts:
          - mountPath: /mlodata1
            name: mlodata1
          - mountPath: /mloraw1
            name: mloraw1
          - mountPath: /scratch
            name: scratch
      volumes:
        - name: mlodata1
          persistentVolumeClaim:
            claimName: runai-mlo-danmoral-mlodata1
        - name: mloraw1
          persistentVolumeClaim:
            claimName: runai-mlo-danmoral-mloraw1
        - name: scratch
          persistentVolumeClaim:
            claimName: runai-mlo-danmoral-scratch